name: espatula
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.4.0
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.7.25
  - aws-c-cal=0.7.3
  - aws-c-common=0.9.25
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.7
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.5
  - aws-sdk-cpp=1.11.379
  - blinker=1.8.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.0
  - ca-certificates=2024.7.4
  - cachetools=5.4.0
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.5
  - decorator=5.1.1
  - easyprocess=1.1
  - entrypoint2=1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - fastcore=1.7.1
  - freetype=2.12.1
  - fuzzywuzzy=0.18.0
  - gazpacho=1.1
  - gitdb=4.0.11
  - gitpython=3.1.43
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=7.2.1
  - importlib_metadata=7.2.1
  - importlib_resources=6.4.2
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - jedi=0.19.1
  - jeepney=0.8.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.11
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - levenshtein=0.25.1
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.9.1
  - libdeflate=1.21
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libparquet=17.0.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2024.1.0
  - mouseinfo=0.1.3
  - msys2-conda-epoch=20160418
  - narwhals=1.4.2
  - nest-asyncio=1.6.0
  - nltk=3.8.2
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyautogui=0.9.54
  - pycparser=2.22
  - pydeck=0.8.0
  - pygetwindow=0.0.9
  - pygments=2.18.0
  - pymsgbox=1.0.9
  - pypdf=4.3.1
  - pyperclip=1.9.0
  - pyrect=0.2.0
  - pyscreenshot=3.1
  - pyscreeze=0.1.30
  - pysocks=1.7.1
  - python=3.12.5
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-levenshtein=0.25.1
  - python-mss=9.0.1
  - python-tzdata=2024.1
  - python-xlib=0.33
  - python_abi=3.12
  - pytweening=1.2.0
  - pytz=2024.1
  - pywin32=306
  - pyyaml=6.0.2
  - pyzmq=26.1.0
  - rapidfuzz=3.9.6
  - re2=2023.09.01
  - referencing=0.35.1
  - regex=2024.7.24
  - rich=13.7.1
  - rpds-py=0.20.0
  - rubicon-objc=0.4.9
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - setuptools=72.1.0
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.1
  - stack_data=0.6.2
  - streamlit=1.37.1
  - tbb=2021.12.0
  - tenacity=8.5.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - tzlocal=5.2
  - ucrt=10.0.22621.0
  - urllib3=2.2.2
  - validators=0.33.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - widgetsnbextension=4.0.11
  - win_inet_pton=1.1.0
  - xlsxwriter=3.2.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.12.3
      - behave==1.2.6
      - chardet==5.2.0
      - cssselect==1.2.0
      - execnet==2.1.1
      - fasteners==0.19
      - filelock==3.15.4
      - h11==0.14.0
      - iniconfig==2.0.0
      - outcome==1.3.0.post0
      - parameterized==0.9.0
      - parse==1.20.2
      - parse-type==0.6.2
      - pdbp==1.5.4
      - pluggy==1.5.0
      - py==1.11.0
      - pynose==1.5.2
      - pyotp==2.9.0
      - pyreadline3==3.4.1
      - pytest==8.3.2
      - pytest-html==2.0.1
      - pytest-metadata==3.1.1
      - pytest-ordering==0.6
      - pytest-rerunfailures==14.0
      - pytest-xdist==3.6.1
      - requests==2.31.0
      - sbvirtualdisplay==1.3.0
      - selenium==4.23.1
      - seleniumbase==4.29.9
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - tabcompleter==1.3.3
      - trio==0.26.2
      - trio-websocket==0.11.1
      - websocket-client==1.8.0
      - wsproto==1.2.0
